### ISSUE TITLE
Question on steps 5-9

### ISSUE THREAD

**Issue by toncho11** [MrSparc/idprom-repair#3]
Thank you for this repository!

I have the impression that steps 5 to 9 are optional. Actually I do not completely understand them.
I think after getting the address in step 4 we can directly proceed to the first write operation:
```
ok 01 address c! 
```
Is that correct? 5 to 9 are rather for visualization?

**Comment by MrSparc** [comment]
Probably the best way to understand each of these commands is taking a look to the OpenBoot 4.x Command Reference Manual. 

OpenBoot represents the interconnected buses and their attached devices as a tree of nodes, called the device tree.  
What are you looking at step 4 is the physical address of the device. 

The OpenBoot prompt interface provides interactive commands for examining and setting memory. With the user interface, you can:
- Read and write to any virtual address.
- Map virtual addresses to physical addresses.
 
 So, you need to map a region of physical address of the EEPROM device into virtual address (address used by software) using  memmap in order to write bytes at the expected offset address. 
I hope this helped you better understand that.

**Comment by toncho11** [comment]
Hi. Thank you.

1) So it is not mapped already to the base address?
2) You do `1fd8 +`, but then you still add this address to the base address when you are entering the values. Why is that? 

Thanks
